### ISSUE TITLE
Doesn't work with Django 3.1.3

### ISSUE THREAD

**Issue by arclogos132** [thornomad/django-hitcount#108]
Doesn't work with Django 3.1.3

**Comment by bimmui** [comment]
Would you mind detailing how it doesn't work with your version of Django? I was considering using this for my project until I saw this issue you opened?

**Comment by pupattan** [comment]
The HttpRequest.is_ajax() method is deprecated as it relied on a jQuery-specific way of signifying AJAX calls, while current usage tends to use the JavaScript Fetch API. Depending on your use case, you can either write your own AJAX detection method, or use the new HttpRequest.accepts() method if your code depends on the client Accept HTTP header.

If you are writing your own AJAX detection method, request.is_ajax() can be reproduced exactly as request.headers.get('x-requested-with') == 'XMLHttpRequest'.

https://docs.djangoproject.com/en/3.1/releases/3.1/#id2
