### ISSUE TITLE
no such table: hitcount_blacklist_ip

### ISSUE THREAD

**Issue by zszep** [thornomad/django-hitcount#114]
After implementing a detail view with django-hitcount, I get the following error message when running the detail view:
`no such table: hitcount_blacklist_ip`

Any help appreciated.

**Comment by MotasemAghbar** [comment]
@zszep Did you run `python manage.py migrate`? if not, you should run it.

Check your database and confirm that `hitcount_blacklist_ip` table is exists

**Comment by zszep** [comment]
I did run `python manage.py makemigrations` and `python manage.py migrate`, but the only tables i have are:
- hitcount_blockedip
- hitcount_blockeduseragent
- hitcount_hit
- hitcount_hi_count
There is no hitcount_blacklist_ip table. After rerunning python `manage.py makemigrations` and python `manage.py migrate` I only get "No migrations to apply".

**Comment by zszep** [comment]
OK. Solved it by deleting the whole database and rerunning the migrations.
