### ISSUE TITLE
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' 

### ISSUE THREAD

**Issue by WEIScott** [thornomad/django-hitcount#119]
I`m using Django==4.0.1. While running the migrate command, the error pops up.

**Comment by WEIScott** [comment]
I use the  command below to install the django-hitcount,
`pip install django-hitcount` 
however, when I look into the hitcount directory in the virtual environment folder "env/lib/site-packages/hitcount", in the models.py the import:
`from django.utils.translation import ugettext_lazy as _`  didn`t update.
And I try to replace the `ugettext_lazy` with `gettext_lazy`, but it doesn't work either.

**Comment by WEIScott** [comment]
Only when I replace the django version4.0.1 with version 3.2, the issue is solved.

**Comment by bashu** [comment]
try django-hitcount == 1.3.5
