### ISSUE TITLE
Getting RuntimeWarning: DateTimeField received a naive datetime.

### ISSUE THREAD

**Issue by shadowym** [thornomad/django-hitcount#26]
Getting RuntimeWarning: DateTimeField received a naive datetime.  This is when TZ=True and TIMEZONE=None

I would like to request an enhancement to make the app datetime aware.
https://docs.djangoproject.com/en/dev/topics/i18n/timezones/#code

**Comment by thornomad** [comment]
I'm going to look at this shortly.

**Comment by thornomad** [comment]
I think this should be fixed now on the master branch; re-open if you are still getting that problem.  Thanks.
