### ISSUE TITLE
Give back the maintainer right

### ISSUE THREAD

**Issue by bashu** [thornomad/django-hitcount#28]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you

**Comment by thornomad** [comment]
Hello sir!  I've finally got back to work on this.  Sorry for the super-lazy delay.  I've updated the local changes I've had sitting around.  If you want to submit pull requests I'm ready!

**Comment by bashu** [comment]
great!
