### ISSUE TITLE
Non-ajax hit recording approach (based on UA list)

### ISSUE THREAD

**Issue by thornomad** [thornomad/django-hitcount#3]
See this [comment thread][1] for reasoning.  Basically, some folks may want to record hits without using JavaScript.

One possible approach: 

- implement a way to import a list of bot User-Agents into our banned UA database (we are already checking that database as it is)
- create our own wrapper for an `object_detail` view that can be used in lieu of the basic `object_detail` view ... only ours will attempt to record a Hit

Add a comment if you have thoughts to this approach.

[1]: http://blog.damontimm.com/django-hitcount-app-count-hits-views/comment-page-1/#comment-17411

**Comment by bashu** [comment]
take a look at https://github.com/bashu/django-popularity-mixin 

PS: I will add documentation soon

**Comment by thornomad** [comment]
Hi @bashu - thanks for sharing that link and is nice to see that something else could have been built with django-hitcount.  Very cool.

**Comment by thornomad** [comment]
This was added in the 1.2 version.
