### ISSUE TITLE
Internationalization !

### ISSUE THREAD

**Issue by RamezIssac** [thornomad/django-hitcount#31]
Found your nice piece of code; One problem thought, no Multilingual support.

I'll be happy to contribute it.

**Comment by thornomad** [comment]
Hi - check out the develop branch. I haven't moved it to master yet but
there is some language support in there. Would love more help. I plan to
pull develop over to master soon ... Just ran out of time.

**Comment by thornomad** [comment]
Hi there - I pulled everything over to Master.  I had a bear of a time with some of the merge conflicts so here's hoping everything is working okay.  Seems pretty good just now on my end.  Take a look at the internationalization and send me a pull request.  I'm not too familiar with the best way to set all that up.  I will close this for now but feel free to re-open with a pull request.
