### ISSUE TITLE
ImportError in django 1.5

### ISSUE THREAD

**Issue by github-account-because-they-want-it** [thornomad/django-hitcount#32]
I have to use **django 1.5** for a project because it uses **django-postman**. I installed **hitcount** like this:
```pip install -e git://github.com/thornomad/django-hitcount.git#egg=django-hitcount```

Here's what I get:

`File "/home/.../src/django-hitcount/hitcount/models.py", line 11, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
ImportError: No module named fields
`
How can I get an older version?.

**Comment by thornomad** [comment]
You can try:

pip install django-hitcount

That will install the older version hosted on pip. You could also try:

pip install -e git://
github.com/thornomad/django-hitcount.git@2.0#egg=django-hitcount

That should grab the 2.0 tag. The current master branch is at Django 1.8.x.
Let me know if that works for you.

If that is the only error you are getting it should be easy to fix by
forming it too -- Django just moved the import location of some of its
content type stuff.

Damon

**Comment by github-account-because-they-want-it** [comment]
thanks for the fast reply.
trying `pip install django-hitcount`:

**Downloading/unpacking django-hitcount
  Could not find any downloads that satisfy the requirement django-hitcount
Cleaning up...
No distributions at all found for django-hitcount
**

trying `pip install -e git://github.com/thornomad/django-hitcount.git@2.0#egg=django-hitcount`:
**
Obtaining django-hitcount from git+git://github.com/thornomad/django-hitcount.git@2.0#egg=django-hitcount
  Updating /home/.../src/django-hitcount clone (to 2.0)
  Could not find a tag or branch '2.0', assuming commit.
fatal: ambiguous argument '2.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  Complete output from command /usr/bin/git reset --hard -q 2.0:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git reset --hard -q 2.0 failed with error code 128 in /home/.../src/django-hitcount

**Comment by thornomad** [comment]
Try 0.2 -- not 2.0. Dyslexia ...

**Comment by thornomad** [comment]
I patched it -- I think this should fix the problem.  I tested it with 1.5.12 ... seemed to work.  You should be able to use:

    pip install -e git://github.com/thornomad/django-hitcount.git#egg=django-hitcount

Let me know how it goes.  Documentation is lacking at this point too.

**Comment by github-account-because-they-want-it** [comment]
Thanks. That worked.
