### ISSUE TITLE
feature to set related_name

### ISSUE THREAD

**Issue by mirzadelic** [thornomad/django-hitcount#39]
How can i get related_name? My model is `Ad`.

**Comment by thornomad** [comment]
Because the `HitCount` model uses a `GenericForeignKey` I believe you would want to use a [reverse generic relation](https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#reverse-generic-relations) on your model.

    class Ad(models.Model):
        ...
        hit_count = GenericRelation(HitCount)

Let me know if this gets you where you need to go.

**Comment by mirzadelic** [comment]
I'm getting error:
```
HitCount has no field named u'object_id'
```

**Comment by thornomad** [comment]
Yea - that's because of an older naming convention.  Try:

    class Ad(models.Model):
        ...
        hit_count = GenericRelation(HitCount
                                    object_id_field='object_pk')

**Comment by mirzadelic** [comment]
Now, i can't get hit count with `ad.hit_count`, it says:
```
StopIteration
```

**Comment by thornomad** [comment]
Will need more info, I think -- what version of Django ... what is the full exception?

**Comment by mirzadelic** [comment]
In template i use: ` {{ ad.hit_count }}`, when i put that, i am getting that error.
Django 1.7.3.

**Comment by thornomad** [comment]
What if you do `{{ ad.hit_count.hits }}` ?

**Comment by mirzadelic** [comment]
Empty :(

**Comment by thornomad** [comment]
Sorry, I didn't read the documentation very carefully ... the `GenericRelation` returns a manager ... because it is not, necessarily, a one-to-one relation between the two objects.  

So, you would want to do:

    hits = ad.hit_count.get().hits

Of course, you would need to have something with hits ... am thinking writing a mixin would be helpful like the one recommended [here](http://stackoverflow.com/a/9295723/181902).

**Comment by mirzadelic** [comment]
Thanks, this works, but it makes request for every ad, and i list 20 ads, so + 20 more sql requests.
How can i make this in `select_related` or `prefetch_related`? That was idea.

**Comment by thornomad** [comment]
Yes - it would.  It would probably make sense to cache the result somehow.  This is a big downside of using a database to track views/hits ... it's expensive.

**Comment by mirzadelic** [comment]
So, there is no solution for this?

**Comment by thornomad** [comment]
I don't think you can do `select_related` with a `GenericRelation`, no.  Have a look at this post for [some ideas](http://stackoverflow.com/a/2943128/181902).

**Comment by mirzadelic** [comment]
:( Thanks.
