### ISSUE TITLE
Support for Non-int object_pk values?

### ISSUE THREAD

**Issue by choiRyan** [thornomad/django-hitcount#42]
Currently, non-integer object_pk values are not supported, right? In my application I'm using UUID values instead of PositiveInteger values for primary keys, and something seems to be unhappy with this, so I'm just checking whether it's expected.

e.g. it tries to insert, for each of these fields respectively:
```
[<django.db.models.fields.PositiveIntegerField: hits>,
 <django.db.models.fields.DateTimeField: modified>,
 <django.db.models.fields.related.ForeignKey: content_type>,
 <django.db.models.fields.PositiveIntegerField: object_pk>]

(0,
 datetime.datetime(2015, 11, 8, 14, 59, 26, 846708, tzinfo=<UTC>),
 18,
 529346511985444997385400981615289)
```

**Comment by thornomad** [comment]
Hi there - you are correct.

https://github.com/thornomad/django-hitcount/blob/2.0/hitcount/models.py#L45

It is looking for a numeric pk.  It follows the docs implementation of a *Generic Relation*.  

https://docs.djangoproject.com/en/1.8/ref/contrib/contenttypes/#generic-relations

It would be easy to fork this and change the `PositiveIntegerField` to a `CharField` or, as you suggest, a `UUIDField`; everything else should work the same.

D

**Comment by choiRyan** [comment]
Yeah, that's exactly what I did :)  thanks for the links!

Also, response time: :+1:

**Comment by thornomad** [comment]
We could maybe add a setting that allows someone to select a different type of `object_pk` field ... that way you wouldn't have to diverge from the codebase.

**Comment by choiRyan** [comment]
Sounds like a good idea!

[Reminding future readers that UUIDField is really a fixed length CharField for most backends (exception being Postgres) and is a relatively new (Django 1.8) feature]:
https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.UUIDField

Half the tests are failing after changing the aforementioned field to UUIDField, but from a quick glance the failure cause is similar for most of these (to do with UUIDs). I will have to look again with more than 0 hours of sleep though...

**Comment by thornomad** [comment]
If you use your `UUIDField` as the primary key does it report that when you do `object.pk` or `object.id` ?  It may just be the hard coding of the tests to a numeric `pk`.

**Comment by thornomad** [comment]
Thinking about this a little with the testing errors ...

1) you need to update the `example_project/blog/models.py` to include a `UUIDField` as the `id`.  Because it is going to default to `AutoField` and that won't work with the change to the hitcount source.

2) The fixtures need to be updated to use a `uuid` and not an `int`

3) I am not sure sqlite supports `uuid` as a primary key ... does it?  I assume you are going to be using postgres but for this app the testing is done in sqlite ... 

I think those may be the three main issues to overcome in the testing!

**Comment by choiRyan** [comment]
Points 1 & 2: Agreed
3: Don't think so, for all backends other than Postgres we could just use a fixed length charfield (as noted in the docs I linked before it says that Django does that for UUIDField anyways for all non-postgres backends)

**Comment by thornomad** [comment]
Okay - well, I tried real quick to just make three changes (hitcount model, blog post model, and fixture) -- but I am not able to get the tests to run.  Choking on the fixture.  Let me know if you are able to get the testing to work somehow.  If I have time a little later I can look into it more.

**Comment by biosini** [comment]
Hello @thornomad, I just cloned the project and changed `object_pk = models.PositiveIntegerField('object ID')` to `object_pk = models.UUIDField('object ID')` and it's working perfectly!
I think would be great if you can add a Django setting so we can dinamically set the needed object ID with default value set to `PositiveIntegerField` like:
`HITCOUNT_OBJECT_ID_FIELD = models.PositiveIntegerField`

I saw this issue and thought that maybe was helpful to others.
Best,
Fabio

**Comment by PeterAugustinak** [comment]
Hi there, I have changed that field to Slug, means
`object_pk = models.PositiveIntegerField('object ID')`
to
`object_pk = models.SlugField(verbose_name='object ID')`

I deleted migrations, created new, migrate, restart app and all, but still getting:
`Field 'object_pk' expected a number but got`

Any advise please?
