### ISSUE TITLE
How to keep HIts in DB forever 

### ISSUE THREAD

**Issue by vaibhav-jain** [thornomad/django-hitcount#45]
First thanks @thornomad for this awesome app.

As docs suggested
`
HITCOUNT_KEEP_HIT_IN_DATABASE = { 'days': 30 }
`
But if someone wants to make them permanent ??

**Comment by vaibhav-jain** [comment]
I see there is a command `./manage.py hitcount_cleanup` So this command should be fired in order to cleanup the Hits, I thought they will be cleaned up automatically . . .  please correct me if I am wrong

**Comment by thornomad** [comment]
The default will leave the Hit indefinitely. That setting is used in conjunction with the management command. If you don't run the command they will persist forever. 

http://django-hitcount.readthedocs.org/en/latest/settings.html#hitcount-keep-hit-in-database

**Comment by vaibhav-jain** [comment]
Thanks @thornomad for clearing my doubt . . .

**Comment by jlariza** [comment]
@thornomad It would be nice to clarify this in the documentation; I also was lost about how it works. Thank you

**Comment by thornomad** [comment]
Okay I can do that. Thanks.
