### ISSUE TITLE
always get zero hitcount

### ISSUE THREAD

**Issue by divinites** [thornomad/django-hitcount#46]
I installed hitcount amd followed  your installation guide. Everything is fine except that all hitcount mever increase and show 0. That is,  if someone click tje countable page, this page will appear in the admin list, but with the  number  0.

**Comment by thornomad** [comment]
Have you tried installing and running the example project (rather than your own project)?

http://django-hitcount.readthedocs.io/en/latest/example_project.html

Test the example project and see if you are still having that problem and, if you are, send me more details (version, any tracebacks, etc).

**Comment by divinites** [comment]
the example works.  the apps also worked for a while. Then I write a new class in the model.py that inherit HitCountMiXin. after migtation, there is a new migration file 0002_auto.py appears in the migration folder， which seems nothing special. then  the counter  stopped changing  in the admin.  Even  after  i  revert this  change  and delete the model. Now if someone visit a page that  was never visited, an entry will be added in the database, but the counter  is  zero. If  it is a visited page, nothing  changes.

**Comment by thornomad** [comment]
Maybe share some of your code?  It is hard to tell without a more concrete example.  Are you inheriting HitCountMixin like this, [in the docs](http://django-hitcount.readthedocs.io/en/latest/installation.html#models)?

**Comment by divinites** [comment]
very simple code,  I am using  mezzanine, blogpost  is  a class in  mezzanine.blog. here is  what i added first  and  deleted  afterwards in models.py


```
class CountableBlogPost(BlogPost, HitCountMixin):
    pass

class AnotherBlogPost(Model, HitCountMixin):
    pass 
    
```

**Comment by thornomad** [comment]
And how were you displaying them ?  

If you do this (below) you are getting `0` even though you see rows counted in the database?

```
# you would access your hit_count like so:
my_model = CountableBlogPost.objects.get(pk=1)
my_model.hit_count.hits                 # total number of hits
```

**Comment by divinites** [comment]
I did nothing. The  fact  is that  after i adding those four  lines,  the  originally  working  hitcount stop updating.  Initially,  i  mimic  your  working example(ajax one),  the hitcount  correctly appeared and updated in the admin console.

**Comment by divinites** [comment]
is it possible that the presence of 0002_auto altered the pk table, so 0001_initial stopped working?

**Comment by thornomad** [comment]
I guess it depends on what the migrations are doing ... what does it say it is changing ?

**Comment by divinites** [comment]
for your info  my blog post templates

```
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n future disqus_tags  staticfiles%}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}
{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}

{% endblock %}
<link rel="stylesheet" href="{% static 'css/share.min.css' %}">
<script src="{% static 'js/social-share.min.js' %}"></script>
<script src="{% static 'hitcount/jquery.postcsrf.js' %}"></script>
<script type="text/javascript">
jQuery(document).ready(function($) {
  // use the template tags in our JavaScript call
  $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK : "{{ hitcount.pk }}" })
    .done(function(data){
      $('<i />').text(data.hit_counted).attr('id','hit-counted-value').appendTo('#hit-counted');
      $('#hit-response').text(data.hit_message);
  }).fail(function(data){
      console.log('POST failed');
      console.log(data);
  });
});
</script>

{% block main %}
	<div class="blog">
	{% block blog_post_main%}
		<div class="blog-item well">
		{% block blog_post_list_post_title %}
			{{block.super}}
		{% endblock %}
		 <div class="blog-meta clearfix">
		{% block blog_post_list_post_metainfo %}
			{{block.super}}
		{% endblock %}
		</div>

			<p>
			{% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
			{% block blog_post_list_post_featured_image %}
<!-- 			<h2>{{total_hits}} + 12345</h2> -->
				{{block.super}}
			{% endblock %}
			{% endif %}
			</p>


		{% block blog_post_list_post_content %}

			{% editable blog_post.content %}
			{{ blog_post.content|richtext_filters|safe }}
			{% endeditable %}

		{% endblock %}
		{% block blog_post_detail_content %}

		{% endblock %}

		{% block read_more%}

		{% endblock %}

		{% block blog_post_detail_keywords %}
			{% keywords_for blog_post as tags %}
			{% if tags %}

			<div class="tag">

				{% for tag in tags %}
				<a href="{% url "blog_post_list_tag" tag.slug %}"> <span class="label label-success"> {{tag}} </span> </a>
				{% endfor %}
			</div>

			{% endif %}
		{% endblock %}

{% block blog_post_detail_sharebuttons %}
<div class="social-share" data-description="神佑之园 —— 一键分享到微博，微信，Facebook，Google"></div>
{% endblock %}
		</div>
	{% endblock %}
	</div>





{% block blog_post_previous_next %}
<ul class="pager">
{% with blog_post.get_previous_by_publish_date as previous %}
{% if previous %}
<li class="previous">
    <a href="{{ previous.get_absolute_url }}"><i class="fa fa-arrow-left"></i> {{ previous }}</a>
</li>
{% endif %}
{% endwith %}
{% with blog_post.get_next_by_publish_date as next %}
{% if next %}
<li class="next">
    <a href="{{ next.get_absolute_url }}">{{ next }} <i class="fa fa-arrow-right"></i>
{% endif %}
{% endwith %}
</ul>
{% endblock %}

{% block blog_post_detail_related_posts %}
{% if blog_post.related_posts.all %}
<div id="related-posts">
<h3>{% trans 'Related posts' %}</h3>
<ul class="list-unstyled">
{% for post in blog_post.related_posts.all %}
     <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}

{% block blog_post_detail_comments %}
{% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
{% endblock %}
{% block inline_javascript %}

{% load staticfiles %}
<script src="{% static 'hitcount/jquery.postcsrf.js' %}"></script>
{% load hitcount_tags %}
{% get_hit_count_js_variables for blog_post as hitcount %}
<script type="text/javascript">
jQuery(document).ready(function($) {
  $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK : "{{ hitcount.pk }}" })
    "hitcount",
    .done(function(data){
      $('<i />').text(data.hit_counted).attr('id','hit-counted-value').appendTo('#hit-counted');
      $('#hit-response').text(data.hit_message);
  }).fail(function(data){
      console.log('POST failed');
      console.log(data);
  });
});
</script>
{% endblock %}
{% endblock %}


```

**Comment by thornomad** [comment]
I'm really not sure where you went wrong; it may be because you migrated from one model to the next ... if you start from scratch using your desired setup (no migrations, just an initial) will it work?

Also, from your copy paste it looks like you are executing the JS twice (unless those are two examples).

**Comment by divinites** [comment]
When i  did  migration, 0002_auto is  like  this:

```

-*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hitcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='object_pk',
            field=models.PositiveIntegerField(verbose_name='object ID'),
        ),
    ]

```

**Comment by thornomad** [comment]
When you render the page is this line providing the correct pk for the `HitCount` object?

     $.postCSRF("{{ hitcount.ajax_url }}", { hitcountPK : "{{ hitcount.pk }}" })

**Comment by divinites** [comment]
Yes, the hitcount.pk is correct. Any other thing to track? I have deleted the duplicated scripts, but seems no difference.

I can provide a test page for you:
[https://www.scislab.com/blog/hitcount-test/](
https://www.scislab.com/blog/hitcount-test/)

**Comment by divinites** [comment]
it works!  cause i corrected an error of js... thanks for your help! issue closed

**Comment by divinites** [comment]
sorry, I need to reopen the issue. The problem is that the number of hitcountPK is wrong. In my case, I have 300+ blogs, but the hitcountPK is over 400.

**Comment by thornomad** [comment]
I wasn't able to view the test site; unfortunately, it's hard for me to guess what the issue is ... if you were able to reproduce the problem through a test case or by using the example site that comes bundled in this repository I can rebuild it on my end and troubleshoot it.  But I am not sure, really, what your problem is at the moment.

The HitcountPK will be different than the number of blogs you have ... especially if you reset the models with a migration.  HTH

**Comment by divinites** [comment]
thanks it magically works again.  although i am still a bit confusing,  i close this issue at this moment. thanks for your help

**Comment by thornomad** [comment]
Okay - thanks for the update.  I am not sure myself what your problem was.  Good luck!
