### ISSUE TITLE
On delete cascade

### ISSUE THREAD

**Issue by mapeveri** [thornomad/django-hitcount#47]
Is posible add on_delete=models.CASCADE to model HitCount:

      @python_2_unicode_compatible
       class HitCount(models.Model):
            ...
            content_type = models.ForeignKey(
                ContentType, related_name="content_type_set_for_%(class)s", on_delete=models.CASCADE)

For remove automatic in model HitCount when occurs on delete event in model parent?.

Thanks!

**Comment by thornomad** [comment]
Hi there -

Yes, I can add that.  It looks like it will be [required by version 2.0](https://docs.djangoproject.com/en/1.9/ref/models/fields/#arguments).  From reading the docs, though, it seems that previous version DEFAULT to using `models.CASCADE` ... so, that is the behavior you _should_ be seeing I think.  Is that not the case?

Thanks for bringing it to my attention.

**Comment by mapeveri** [comment]
No, it does not work. I'll keep trying, can I have something wrong.

**Comment by thornomad** [comment]
Okay - I started playing with test case and it seems to work for me; will look at more shortly.

**Comment by thornomad** [comment]
I added the line for 2.0 and added a test case ... seems to work on my end.  Good luck!

**Comment by mapeveri** [comment]
Thank you so much! :)
