### ISSUE TITLE
Using hitcount in Generic ListView

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [thornomad/django-hitcount#49]
How to use hitcount in generic list view. I can't figure it out it pops up quite a few errors.
I got a generic DetailView and it works perfectly fine for it. But for generic ListView it does not simply work for me. I just need to set it up for a list and need to be able to see 6 products with most views.
Your help is appreciated for creating nice and needful piece of code but if you can help to solve this problem it will be a great help.
Cheers.
:-)

**Comment by thornomad** [comment]
Hello there - so, `django-hitcount` comes with a built-in `HitCountDetailView`; however, it does not have a built-in `HitCountListView`.  You will have to write your own view to accomplish this.  You can access your `HitCount` model and retrieve the six `HitCount`s with the most `hits`.  Does this make sense?

**Comment by MUDASSARHASHMI** [comment]
Thanks I was trying to count hit on whole list and then filter with max values. I figured it out. Thanks for help.

**Comment by thornomad** [comment]
Glad you got it sorted.  Thanks for the update.
