### ISSUE TITLE
Create relationship with hitcount

### ISSUE THREAD

**Issue by UncleJimmy** [thornomad/django-hitcount#50]
I want to create a relationship using my own model with hitcount model, so I can filter on the hitcount numbers with Django Filtering, such as annotate().filter()

get @property from HitCountMixin seems not working to implement that.

Thanks

**Comment by thornomad** [comment]
Can you share your code and the console steps you are taking and errors you are getting thanks.

**Comment by thornomad** [comment]
Check out this issue as well, it may have your answer.  Best of luck:

https://github.com/thornomad/django-hitcount/issues/51
