### ISSUE TITLE
Sort by amount of views

### ISSUE THREAD

**Issue by theWaR13** [thornomad/django-hitcount#51]
Hello. I'm trying to implement a sorting by an amount of views. Is it possible with your app? Thanks in advance.

Piece of my code:
```
    def get(self, request, *args, **kwargs):
        user = request.user
        entries = Entry.objects.all().order_by('-date') #i need amount of views here

        return render(request, path/to.html', context={
            'entries': entries,
            'user': user
        })
```

**Comment by thornomad** [comment]
I believe if you create a `GenericRelation` in your `Entry` model ... as seen in the example project:

https://github.com/thornomad/django-hitcount/blob/master/example_project/blog/models.py

You then can sort like:

    Entry.objects.order_by("hit_count_generic__hits")

**Comment by theWaR13** [comment]
Yes, it works! Thanks a lot for your help! :)

**Comment by dE1l** [comment]
@thornomad, add this information to documentation, please

**Comment by sandeepimpressads** [comment]
If anyone is having issue of `Entry.objects.order_by("hit_count_generic__hits") ` not working expected, it could be due to the null value in database. then use it like this
`from django.db.models import  F
Entry.objects.order_by(F("hit_count_generic__hits").desc(nulls_last=True))`
