### ISSUE TITLE
'function' object has no attribute 'hits'

### ISSUE THREAD

**Issue by viirak** [thornomad/django-hitcount#52]
got my model inherit from HitCountMixin
calling mymodel.hit_count.hits always cause this error:
'function' object has no attribute 'hits'

any suggestion, please?

**Comment by thornomad** [comment]
Check out the example project included in this repo:

http://django-hitcount.readthedocs.io/en/latest/example_project.html

The setup is down here:

http://django-hitcount.readthedocs.io/en/latest/example_project.html
