### ISSUE TITLE
Installation error after Syncdb

### ISSUE THREAD

**Issue by Gun1tSurya** [thornomad/django-hitcount#53]
File "/home/dhar/envs/at_env/local/lib/python2.7/site-packages/hitcount/models.py", line 11, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
ImportError: No module named fields

**Comment by thornomad** [comment]
What verison of Django are you using ?

**Comment by Gun1tSurya** [comment]
Django 1.6.4

**Comment by thornomad** [comment]
http://django-hitcount.readthedocs.io/en/latest/overview.html#requirements-and-compatibility
