### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by cdvv7788** [thornomad/django-hitcount#54]
Is this project compatible with django-1.10? If so, we should change the package requirements to be django<1.11 instead of django==1.9.6. The requires.io badge shows the insecure label because of that.

**Comment by thornomad** [comment]
It should be; that's just the included test_project that is coming back insecure.  The tox settings test against 1.10.  I can update it though.  thanks!

**Comment by zmrenwu** [comment]
I use it in django 1.11 and it works well.
