### ISSUE TITLE
advice: my website is visit for 100k

### ISSUE THREAD

**Issue by CARocha** [thornomad/django-hitcount#55]
Hi, when  this happend 100k visit this site
When the visits are strong, the site gets super slow, I think the apps start writing to the database and that causes slowness
What can I do for the 10k in a few minutes? and databases writen and  not slow down the site?
What advice do you give me?

**Comment by thornomad** [comment]
Honestly - this little app is not designed for high volume traffic.  As you've noticed, it's very database intensive and heavy traffic will wreak havoc.

You could try caching some of the values for the _counts_ themselves; however, that isn't going to address the problem of attempting to track each user page hit.

There is a helper to clean-up stale hits in the DB to keep the table smaller, but I doubt that is really the problem.

**Comment by CARocha** [comment]
@thornomad you are right :/ thank for you help, I will think or investigate more about how to count visits/hit :)
