### ISSUE TITLE
Invalid block tag 'get_hit_count_javascript' --- Please Help i need it to be done asap!

### ISSUE THREAD

**Issue by ZaibiMughal** [thornomad/django-hitcount#57]
Invalid block tag on line 107: 'get_hit_count_javascript'. Did you forget to register or load this tag?

**Comment by thornomad** [comment]
Have you followed all the steps outlined:

http://django-hitcount.readthedocs.io/en/latest/installation.html

Did you forget to register or load the tag?

```
# remember to load the tags first
{% load hitcount_tags %}
```

**Comment by ZaibiMughal** [comment]
Yes! I have placed it at the top. But now i am getting this error. Check this screen shot: http://prntscr.com/f1637p
Actually i am new to django. I spend 3 days to understand your code and then to implement it in my code. But still i got no success. But now from your reply i am very happy that the developer of this package is so interactive with his users. Thanks for replying. If you want then I can show you the code!

**Comment by thornomad** [comment]
Did you register the namespace in urls.py? I would guess you missed a step of the tutorial.

**Comment by ZaibiMughal** [comment]
ohh i just placed it in the app urls.py. Got it working now Thanks alot! you are great man! :)
Now only 1 issue left. On the first click it still shows 0. When i click for the 2nd time then it shows 1 and then everything works fine.

**Comment by ZaibiMughal** [comment]
And have you created any package to implement commenting option? Really want to see this from you as your this package is so user-friendly and awesome.

**Comment by thornomad** [comment]
No - I don't have a package for commenting.  But I'm sure they are out there.  Good luck!
