### ISSUE TITLE
How to sort my products based on your hitcount package?

### ISSUE THREAD

**Issue by ZaibiMughal** [thornomad/django-hitcount#58]
I have used your hit count package in my project.  But i am unable to get the hitcounts per product in my views. The main reason that i want to get hit counts is that i want to sort my products based on hit counts. 
Yes! There is a different model named "hitcounts" in admin view that shows the total hit. but how can i sort a different model products based on this "hitcount" model? 
My code:

class Product(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=500)
    hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')

    def get_absolute_url(self):
        return reverse('products:detail',
                      kwargs={'product_id': self.pk})
    def __str__(self):
        return self.title + ' - ' + str(self.id)

**Comment by aatishnn** [comment]
@ZaibiMughal see this https://github.com/thornomad/django-hitcount/issues/51

**Comment by ZaibiMughal** [comment]
Oh yes! Thanks a lot. It's working :)
