### ISSUE TITLE
{% get_hit_count for [object] within ["days=1,minutes=30"] %} not working

### ISSUE THREAD

**Issue by sowinski** [thornomad/django-hitcount#61]
Hi,

I am using django 1.10 with django-hitcount and can't use this exmaple from the docs:
`{% get_hit_count for building  %}`
This is working, but if i add the within statement I got this error:
`{% get_hit_count for building within ["days=1,minutes=30"] %}`
Template Error:

> invalid literal for int() with base 10: '1]'

Any idea what could be wrong? Without the "within" statement, everythink works fantastic :)

**Comment by thornomad** [comment]
Try:

    {% get_hit_count for building within "days=1,minutes=30" %}

I think that should do it.  The brackets were just to help indicate an example of what could go there.

Damon
