### ISSUE TITLE
How to use django-hitcount in a SPA?

### ISSUE THREAD

**Issue by mapeveri** [thornomad/django-hitcount#62]
How can I use django-hitcount in a spa application that is developed in ember?

**Comment by thornomad** [comment]
this is a django-app -- you would have to rewrite it as an ember-addon I would assume.  Not sure there is any way to port it directly as one is in Python and the other in Javascript.

**Comment by mapeveri** [comment]
@thornomad Perfect, I'll investigate a little. Thank you!
