### ISSUE TITLE
Missing on_delete argument in ForeignKey fields

### ISSUE THREAD

**Issue by mattoufoutu** [thornomad/django-hitcount#65]
Django 2.0 requires `ForeignKey` fields to explicitly define the deletion behavior. Using hitcount with Django 2.0 therefore fails when applying migrations:

```python
  File "/home/mde/.virtualenvs/XXXX-YLXBf2NZ/lib/python3.5/site-packages/hitcount/models.py", line 118, in Hit
    user = models.ForeignKey(AUTH_USER_MODEL, null=True, editable=False)
TypeError: __init__() missing 1 required positional argument: 'on_delete
```

This can be fixed by simply adding a `on_delete=models.CASCADE` argument to `ForeignKey` fields. Should I submit a PR for this? (has the project been tested with Django 2.0? Or should I test it a bit more and maybe submit a larger PR to make it compatible?)

**Comment by thornomad** [comment]
This project has not been tested on 2.0. Am happy to merge if we can
updating the testing and it doesn’t break anything !

**Comment by thornomad** [comment]
This was fixed with the latest release.  Thanks for opening the issue.
