### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'property'

### ISSUE THREAD

**Issue by guideo** [thornomad/django-hitcount#72]
So, I'm sure I'm doing something wrong but I can't figure out what.

I've been following the docs and this is what I have so far:  
- pip install...
- settings.py with 'hitcount'
- then on **views.py** (my model is named Artigo):
`hit_count = HitCount.objects.get_for_object(Artigo)`

This line is giving me the error from the issue title:  
*int() argument must be a string, a bytes-like object or a number, not 'property'*

I haven't done anything else than this. What am I missing?  
I've also tried doing **class Artigo(models.Model, HitCountMixin):** but then when I try to makemigrations I get **No changes detected**

**Comment by jebaaa** [comment]
same issue here. Can't get it work with drf, tried this way and few others also

**Comment by n-agi** [comment]
You should pass the actual model `instance`, not model itself.

**Comment by bashu** [comment]
> You should pass the actual model instance, not model itself.

correct!

**Comment by bashu** [comment]
> I've also tried doing class Artigo(models.Model, HitCountMixin): but then when I try to makemigrations I get No changes detected

see https://github.com/thornomad/django-hitcount/blob/develop/hitcount/models.py#L181, there nothing except `hit_count` method
