### ISSUE TITLE
Get top 10 objects with highest hit count

### ISSUE THREAD

**Issue by vinpalace** [thornomad/django-hitcount#75]
To get top 10 hits with highest hit count I just use  `HitCount.objects.all()[:10]`. But this comes with a disadvantage. Whenever I delete the object that this particular hit is referencing to. It leaves an empty entry. I am unsure of what is happening. 

What I'm doing now in my views
`HitCount.objects.all()[:10]`

and in my templates
`popular_post.content_object.content`

Once the content_object is deleted using admin panel. The hit field becomes empty. 

I could write a line to delete the entry corresponding to the object_pk from the table but isn't it supposed to delete automatically?

**Comment by bashu** [comment]
> I could write a line to delete the entry corresponding to the object_pk from the table but isn't it supposed to delete automatically?

hmm, when I delete Post object (from example_project) I got this, see screenshot :

![Screenshot 2020-07-07 15 00 10](https://user-images.githubusercontent.com/144783/86742869-a40f1000-c062-11ea-9f49-676a96841ea4.png)

**Comment by bashu** [comment]
feel free to re-open, if it's not working
