### ISSUE TITLE
ACTIVE HIT

### ISSUE THREAD

**Issue by kwhandy** [thornomad/django-hitcount#79]
Hello everyone!

Does anyone know how to set
1. the HITCOUNT_KEEP_HIT_ACTIVE  = {'months' : 9999999999999999999999999999999999999999} or infinity?
2. the HITCOUNT_KEEP_HIT_IN_DATABASE = {'months' : 9999999999999999999999999999999999999999999} or infinity?

I need to store view count and not return or decrease anymore but when I set like above, this package return error.

I realy appreciate for your help, thanks:)

**Comment by bashu** [comment]
hey @kwhandy `months` are not supported by timedelta, you can try `{"days": 365 * 9999}` for 9999 years

**Comment by bashu** [comment]
feel free to re-open issue, if it doesn't solve your problem
