### ISSUE TITLE
version 1.3.1 migrate error

### ISSUE THREAD

**Issue by shiveringbulbul** [thornomad/django-hitcount#80]
after python manage.py migrate
the error occurs:

`(1170, "BLOB/TEXT column 'object_pk' used in key specification without a key length")`

then I switch to version 1.3.0
it works

ver. 1.3.1 will fail in MySQL

**Comment by mshipman** [comment]
I can confirm I have the same problem running MariaDB 10.1.41 on Ubuntu 18.04.1

Seems to be a side-effect from changing HitCount's object_pk to a TextField in e5f5dfb8b4af814fc564016dad297eacd7b4c4b2

Downgraded to 1.3.0 and it works fine.

(This project is a really helpful Django app, by the way!)

**Comment by sowinski** [comment]
Any solution for this bug? I have the same problem...

**Comment by bashu** [comment]
will fix in 1.3.3 / 2.0

**Comment by sajjadafridi** [comment]
I have the same problem on window mysql django 3.0

**Comment by sowinski** [comment]
Is there a release date for 1.3.3 ?

**Comment by MahmudulHassan5809** [comment]
I still  got this error **(1170, "BLOB/TEXT column 'object_pk' used in key specification without a key length")**  in migrations for both django 2 & 3 . I am using mysql Database.

**Comment by bashu** [comment]
hey @MahmudulHassan5809 can you try https://github.com/thornomad/django-hitcount/pull/98 ?

**Comment by bashu** [comment]
to @shiveringbulbul , @mshipman , @sowinski , @sajjadafridi , @MahmudulHassan5809  run

```shell
pip install -U django-hitcount
```

**Comment by MahmudulHassan5809** [comment]
It is Working Now.
