### ISSUE TITLE
PostgreSQL: ERROR: operator does not exist: integer = text

### ISSUE THREAD

**Issue by Piecio** [thornomad/django-hitcount#83]
If you have the same problem change in hitcount/models.py:
...
object_pk = models.TextField('object ID') back to:
object_pk = models.PositiveIntegerField('object ID')
then run makemigrations & migrate

**Comment by bashu** [comment]
@Piecio better try this:
```sql
create function pg_catalog.text(int) returns text immutable language sql as $$select textin(int4out($1))$$;
create cast (int as text) with function pg_catalog.text(int) as implicit;
```

**Comment by Piecio** [comment]
@bashu thank you for this solution, but for my specific case object_pk = models.PositiveIntegerField is enought. 
As I understand the main reason you changed object_pk to models.TextField was the ability to be used with strings or there was another reason?

**Comment by bashu** [comment]
> As I understand the main reason you changed object_pk to models.TextField was the ability to be used with strings or there was another reason?

non-integer primary keys, yes! in my case UUID as PK
