### ISSUE TITLE
Querying hit count for a particular day

### ISSUE THREAD

**Issue by abhiabhi94** [thornomad/django-hitcount#85]
Firstly, thanks you for the application. I was trying to write my own application for counting hits but ended up making it too complex.
[Here](https://github.com/thornomad/django-hitcount/blob/ebbb555e61755bb3af4731ab7620f6ea527226e3/hitcount/models.py#L87) `self.hit_set` is used for filtering `hits` after a particular time period.
I wanted to use `hits` obtained on a particular day. Also, I couldn't find anywhere in the repository `hit_set`. I was looking for its definition out of curiosity and also had a use case. Any helps in this regard?

**Comment by abhiabhi94** [comment]
In my case, I was able to calculate the view count on a particular day using the `Hit` module:
```
from hitcount.models import Hit

Hit.objects.filter(created__day=day, hitcount=obj.hit_count).count()
```
where `obj` is the object whose `hit count` is required.

**Comment by bashu** [comment]
> I wanted to use hits obtained on a particular day. Also, I couldn't find anywhere in the repository hit_set. I was looking for its definition out of curiosity and also had a use case. Any helps in this regard?

to understand where `hit_set` comes from, read https://docs.djangoproject.com/en/3.0/ref/models/relations/#related-objects-reference

**Comment by bashu** [comment]
> I am not sure this is the most efficient way since it does make use of the GenericForeignKey set up inside the HitCount model.

looks okay! also you can try something like this:
```python
hit_count = HitCount.objects.get_for_object(obj)
hit_count.hit_set.filter(created__day=day).count()  # NOTE: related Hit objects may be purged from DB, read about HITCOUNT_KEEP_HIT_IN_DATABASE settings
```
