### ISSUE TITLE
How to fix python_2_unicode_compatible

### ISSUE THREAD

**Issue by marlon01** [thornomad/django-hitcount#86]
We need to remove from django.utils.encoding import python_2_unicode_compatible
and @python_2_unicode_compatible from models.py
it'll fix the python_2_unicode_compatible import error

**Comment by bmull** [comment]
Would love to see this resolved.

**Comment by bmull** [comment]
This was actually fixed by @bashu's latest deploy (from #88) , but the release number needs to be bumped to 1.3.2

**Comment by bashu** [comment]
@bmull and @marlon01 I will fix that soon

**Comment by MalachiDraven** [comment]
Has this been fixed? Just installed today, still 1.3.1 and still giving this error with django 3.0

**Comment by venomone** [comment]
also waiting for this, woule be awesome to see an update here soon ;)

**Comment by sthasam2** [comment]
So the newer django (don't know exactly which version, maybe since 3.0) has removed 'python_2_unicode_compatible' module, hence the import error. 
The ugly way of solving this would be to delete all code lines related to this module in the _models.py_ file of the hitcount code.

**Comment by legitcode267** [comment]
Doesn't fixed? waiting...

**Comment by timwilson** [comment]
Any update on this?

**Comment by cemarguvanli** [comment]
any plan to fix this?

**Comment by timwilson** [comment]
How much pizza or beer would it take to get the Django 3.x-compatible release out the door? I will gladly contribute! 😀

**Comment by bashu** [comment]
try to run `pip install -U django-hitcount`
