### ISSUE TITLE
Does not support django 3.0?

### ISSUE THREAD

**Issue by leekyuchang** [thornomad/django-hitcount#87]
Does not support django 3.0?

**Comment by vinpalace** [comment]
Yea it throws error, 

`  File "/Users/vineeth/envs/codingpupv2/lib/python3.7/site-packages/hitcount/models.py", line 10, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (/Users/vineeth/envs/codingpupv2/lib/python3.7/site-packages/django/utils/encoding.py)`

**Comment by bmull** [comment]
This is a duplicate of #86.

**Comment by bashu** [comment]
fixed in 1.3.2
