### ISSUE TITLE
jQuery in no conflict mode

### ISSUE THREAD

**Issue by tgautier** [thornomad/django-hitcount#9]
Hi,

I'm using django-hitcount and I'm very satisfied (thanks for your work), but I have a problem with jQuery since my website is using prototype and scriptaculous for all my js/ajax needs. I have a conflict problem when importing the 3 frameworks (prototype, scriptaculous and jquery), either jquery or the scriptaculous/prototype couple is not working, depending on my import order.

Would it be possible to use jQuery in no conflict mode to be able to use django-hitcount (and so jquery) with other majors js frameworks?

I did the following to resolve my conflict problem:

First my head includes
	{% load hitcount_tags %}
	<script type="text/javascript"></script>

And I changed the following in templatetags/hitcount_tags.py
	--- a/hitcount/templatetags/hitcount_tags.py
	+++ b/hitcount/templatetags/hitcount_tags.py
	@@ -153,7 +153,7 @@ class GetHitCountJavascript(template.Node):
	         obj, created = HitCount.objects.get_or_create(content_type=ctype, 
	                         object_pk=object_pk)
 
	-        js =    "$.post( '" + reverse('hitcount_update_ajax') + "',"   + \
	+        js =    "jQuery.post( '" + reverse('hitcount_update_ajax') + "',"   + \
	                 "\n\t{ hitcount_pk : '" + str(obj.pk) + "' },\n"         + \
	                 "\tfunction(data, status) {\n"                         + \
	                 "\t\tif (data.status == 'error') {\n"                  + \
	@@ -172,7 +172,7 @@ def get_hit_count_javascript(parser, token):
 
	     <script src="/media/js/jquery-latest.js" type="text/javascript"></script>
	     <script type="text/javascript"></script> 

Thanks.

**Comment by thornomad** [comment]
I've significantly changes how the javascript is handled; it should be up to the user now to implement the jQuery in a way that suits them and hopefully this fixes your issue.
