### ISSUE TITLE
order_by("hit_count_generic__hits") gives django.db.utils.ProgrammingError

### ISSUE THREAD

**Issue by ansuman13** [thornomad/django-hitcount#90]
Following from the issue #51,
i am running Python 3.6 with Django 2.2 
I have a model Product 
`class Product(models.Model, HitCountMixin):
    ... `
    `
         hit_count_generic = GenericRelation(
        HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation')`

when using 
`Product.objects.order_by('hit_count_generic__hits')`
gives ->
`...    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: operator does not exist: integer = text
LINE 1: ... "hitcount_hit_count" ON ("pharmacy_product"."id" = "hitcoun...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.`

How to solve this.

**Comment by webconexus** [comment]
I have the same problem.

**Comment by letsgogeeky** [comment]
If you're using `PostgreSQL` you'll be facing this problem because the Postgre engine does not perform implicit type conversion. 

To fix the problem you have 2 options with `PostgreSQL`:
1- Change your model primary key to `TextField` and manage it manually (Not recommended)
2- Take a copy of hitcount and modiify `HitCount` model by changing `object_pk` type to be:
`object_pk = models.AutoField()` or `object_pk = models.UUIDField()` according to your own model setup.

**Comment by mnsrknp** [comment]
@letsgogeeky 

`object_pk = models.PositiveIntegerField()` worked for me.

**Comment by MotasemAghbar** [comment]
@ansuman13  @webconexus 
I've faced the same issue, I've solved it by downgrade hit count to 1.3.0 version.

**Comment by bashu** [comment]
will fix it in 1.3.3 / 2.0

**Comment by naeem-akhtar** [comment]
> @letsgogeeky
> 
> `object_pk = models.PositiveIntegerField()` worked for me.

Can you please tell me how and where you have modified this field. I am fairly new to Django and not able to implement it myself?

**Comment by 100KG-AFRY** [comment]
Just +1ing this issue. Downgrading to 1.3.0 (or any other version for that matter) or downloading a copy and changing the types did not work.

**Comment by ajohnclark** [comment]
Same 1.3.0 downgrade didn't work either, will wait for next version. Thanks for the great simple hit counting tool regardless.

**Comment by sowinski** [comment]
Please release 1.3.3 :)

**Comment by bashu** [comment]
to @ajohnclark and @sowinski can you try https://github.com/thornomad/django-hitcount/pull/98 ?

**Comment by ajohnclark** [comment]
> to @ajohnclark and @sowinski can you try #98 ?

Migrates with latest wagtail/django/Postgresql and also functions properly. Thank you!

**Comment by bashu** [comment]
to @ansuman13 , @webconexus , @letsgogeeky, @mnsrknp , @MotasemAghbar , @100KG-AFRY , @ajohnclark run

```shell
pip install -U django-hitcount
```
