### ISSUE TITLE
why it is not working with the function based view?

### ISSUE THREAD

**Issue by cavinblake** [thornomad/django-hitcount#92]
i'm using function based view for the post detail. The docs said its with the the generic_detail_view. but when i using it in function based detail its not working.

**Comment by bashu** [comment]
hey @cavinblake how can I reproduce it?

**Comment by bashu** [comment]
show me example?

**Comment by bashu** [comment]
see https://github.com/thornomad/django-hitcount/issues/76#issuecomment-654659958
