### ISSUE TITLE
cache blacklisted ips and black listed user agents

### ISSUE THREAD

**Issue by sandeepbalagopal09** [thornomad/django-hitcount#96]
The call to HitCountMixin.hit_count(self.request, hit_count) is querying blacklisted ips and black listed user agents tables. Is it possible to cache these objects ? In our set up we don't update these tables very often. These queries in each hit is expensive.

**Comment by bashu** [comment]
hey @sandeepbalagopal09 you can try https://github.com/Suor/django-cacheops, for example
```python
CACHEOPS_DEFAULTS = {
    'timeout': 60*60
}
CACHEOPS = {
    'hitcount.*': {'ops': 'all'},
    ...
}
```

**Comment by bashu** [comment]
feel free to re-open issue, if it doesn't solve your problem
